name: docker

on:
  push:
    paths:
      - WhereWhenServer/**
      - Dockerfile

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push release
        if: ${{ startsWith(github.ref, 'refs/tags/') }}
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: rockajima/wherewhen:v${{ github.ref_name }},rockajima/wherewhen:latest
      - name: Build and push unstable
        if: ${{ !startsWith(github.ref, 'refs/tags/') }}
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: rockajima/wherewhen:v${{ github.sha }},rockajima/wherewhen:unstable